import { DEVICE_HEIGHT, DEVICE_WIDTH } from "./dimentions";

export const BIG_MARGIN_VERTICAL = DEVICE_HEIGHT * 0.01;
export const SMALL_MARGIN_VERTICAL = DEVICE_HEIGHT * 0.008;
export const BIG_MARGIN_HORIZONTAL = DEVICE_WIDTH * 0.01;
export const SMALL_MARGIN_HORIZONTAL = DEVICE_WIDTH * 0.008;

export const PADDING_VERTICAL = DEVICE_HEIGHT * 0.02;
export const PADDING_HORIZONTAL = DEVICE_WIDTH * 0.01;
