export enum AddNewConnectionActionTypes {
  GET_RESULTS_PATIENTS = "GET_RESULTS_PATIENTS",
  GET_RESULTS_SUPERVISORS = "GET_RESULTS_SUPERVISORS",
  SET_IS_TYPING = "SET_IS_TYPING",
  SET_USER_PREFIX = "SET_USER_PREFIX",
}
